# Default values for awx-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# awx_web, awx_task, memcache and rabbitmq are deployed in the same pod
awx_web:
  image:
    repository: ansible/awx_web
    tag: 7.0.0
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

awx_task:
  image:
    repository: ansible/awx_task
    tag: 7.0.0
    pullPolicy: Always
  resources:
    requests:
      cpu: 1500m
      memory: 2Gi

awx_rabbitmq:
  image:
    repository: ansible/awx_rabbitmq
    tag: 3.7.4
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 2Gi

awx_memcached:
  image:
    repository: memcached
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

# Chart values https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
postgresql:
  install: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 9.6
  postgresqlUsername: awx
  postgresqlPassword: awxpass
  postgresqlDatabase: awx
  persistence:
    enabled: true
  metrics:
    enabled: false
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m

ca_trust_dir:
  enabled: false
  path: /etc/pki/ca-trust/source/anchors

project_data_dir:
  enabled: false
  path: /var/lib/awx/projects

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - awx-k8s.example.com
  annotations:
    # {}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # kubernetes.io/tls-acme: "true"
  tls:
    # []
    # Secrets must be manually created in the namespace.
    - secretName: ssl-cert
      hosts:
        - awx-k8s.example.com

controller:
  kind: StatefulSet
  replicaCount: 1 # DO NOT CHANGE THIS VALUE
  annotations: {}
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

quota:
  enabled: false
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 10Gi

secret_key: awxsecret
admin_user: admin
admin_password: password
pg_username: awx
pg_password: awxpass
pg_admin_password: postgrespass
pg_database: awx
pg_port: 5432
rabbitmq_user: awx
rabbitmq_password: awxpass
rabbitmq_erlang_cookie: cookiemonster
insights_url_base: "https://example.org"

configure_ldap:
  enabled: true
  allow_anonymous_bind: true
  ldap_bind_username: changeme # change this if allow_anonymous_bind: false
  ldap_bind_password: changeme # change this if allow_anonymous_bind: false
  ldap_bind_ou: "ou=people,dc=example,dc=com" # change this if allow_anonymous_bind: false
  ldap_server_uri: "ldap://192.168.1.2:389"
  ldap_user_search: "ou=people,dc=example,dc=com"
  ldap_group_search_dn: "ou=ExampleGroup,ou=CompanyGroups,dc=example,dc=com"
  ldap_superuser_group: "CN=Admin-Group,ou=CompanyGroups,dc=example,dc=com"
  ldap_organizations:
    Group1:
      admins: "CN=Group1,ou=CompanyGroups,dc=example,dc=com"
      remove_admins: true
    Group2: 
      admins: "CN=Group2,ou=CompanyGroups,dc=example,dc=com"
      remove_admins: true
    Group3:
      admins: "CN=Group3,ou=CompanyGroups,dc=example,dc=com"
      remove_admins: true

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
