{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: ssl-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: changeme
  tls.key: changeme
type: kubernetes.io/tls

---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  secret_key: {{ .Values.secret_key | b64enc }}
  admin_password: {{ .Values.admin_password | b64enc }}
  pg_password: {{ .Values.pg_password | b64enc }}
  rabbitmq_password: {{ .Values.rabbitmq_password | b64enc }}
  rabbitmq_erlang_cookie: {{ .Values.rabbitmq_erlang_cookie | b64enc }}
  environment_sh: {{ tpl (.Files.Get "files/environment.sh") . | b64enc | quote }}
  credentials_py: {{ tpl (.Files.Get "files/credentials.py") . | b64enc | quote }}