apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx
  namespace: {{ .Release.Namespace }}

---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: rabbitmq
  labels:
    app: {{ .Release.Name }}
    type: LoadBalancer
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: {{ .Release.Name }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: awx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}-web-svc
spec:
  type: "NodePort"
  ports:
    - name: http
      port: 80
      targetPort: 8052
  selector:
    name: {{ .Release.Name }}-web-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rmq-mgmt
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}-rmq-mgmt
spec:
  type: ClusterIP
  ports:
    - name: rmqmgmt
      port: 15672
      targetPort: 15672
  selector:
    name: {{ .Release.Name }}-web-deploy

---
